[project]
name = "world-pop-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "ruff>=0.8.0",
    "streamlit>=1.40.2",
]
